name: Ping Database

on:
  schedule:
    - cron: '0 0 */5 * *'  # Runs every 5 days at midnight UTC

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - name: Ping API route
      run: curl https://next-marketplace-git-main-sams-projects-2d55d388.vercel.app/api/ping-db