name: Ping Database

on:
  schedule:
    - cron: '0 5 * * 0,3,5'
  workflow_dispatch:  # Add this line to enable manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - name: Ping API route
      run: curl https://next-marketplace-git-main-sams-projects-2d55d388.vercel.app/api/ping-db
